name: "Terraform"

# .github/workflows/ folder and terraform.yaml are created manually
# This workflow triggers on a push to the main branch.

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    env: # These are paths to credentials folder
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout # This step clones the repository into the remote GitHub Actions runner workspace
        uses: actions/checkout@v2

      - name: Setup Terraform # Install Terraform on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.0.1"
          terraform_wrapper: false

      - name: Terraform initialise # Initialize the Terraform backend
        id: init
        run: terraform init

      - name: Terraform planning # Plan the Terraform deployment
        id: plan
        run: terraform plan

      # - name: Terraform apply # Apply the Terraform infrastructure
      #   id: apply
      #   run: terraform apply --auto-approve

      # Uncomment the below block if you want to destroy the infrastructure after X days
      - name: Terraform destroy
        id: destroy
        run: terraform destroy --auto-approve
